/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatClientProperties;
import controllers.UnitController;
import exceptions.EntityAlreadyExistException;
import exceptions.ValidationException;
import java.sql.SQLException;
import model.Unit;
import myInterfaces.Refreshable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import raven.toast.Notifications;

/**
 *
 * @author vidur
 */
public class AddNewUnitFrame extends javax.swing.JFrame implements Refreshable{

    /**
     * Creates new form AddNewUnitFrame
     */
    final UnitController controller;
    private static final Logger logger = LoggerFactory.getLogger(AddNewUnitFrame.class);
    private Refreshable refreshable;
    public AddNewUnitFrame() {
        initComponents();
        controller = new UnitController();
        setAlwaysOnTop(true);
        initTheme();
    }
    
    public void setRefreshable(Refreshable re){
        this.refreshable = re;
    }
    
    @Override
    public void refresh(){
        if(refreshable != null){
            refreshable.refresh();
        }

    }

    private void initTheme() {
        lbl_titile.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:$h1.font");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titile = new javax.swing.JLabel();
        panelLogin1 = new components.PanelLogin();
        jLabel2 = new javax.swing.JLabel();
        tf_unit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lbl_titile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titile.setText("Add New Unit");

        jLabel2.setText("Unit Name");
        panelLogin1.add(jLabel2);
        panelLogin1.add(tf_unit);
        panelLogin1.add(jLabel3);

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelLogin1.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_titile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Unit unit = new Unit(0, tf_unit.getText());
        try {
            controller.Add(unit);
            Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER, "Successfully Added Unit!");
            refresh();
            this.dispose();
        } catch (ValidationException ex) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_CENTER, ex.getMessage());
            logger.info(ex.getMessage());

        } catch (SQLException ex) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_CENTER, ex.getMessage());
            logger.error(ex.getMessage());

        } catch (EntityAlreadyExistException ex) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_CENTER, ex.getMessage());
            logger.info(ex.getMessage());

        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_titile;
    private components.PanelLogin panelLogin1;
    private javax.swing.JTextField tf_unit;
    // End of variables declaration//GEN-END:variables
}
